### ISSUE TITLE
А всегда ли объекты моделей нужно создавать через let?

### ISSUE THREAD

**Issue by jeudesprits** [Riim/Maraquia#2]
Методом тыка понял, что модели созданные через `const` при сохранении, собственно сохраняются в коллекцию без полей(кроме `_id`). Почему это происходит? И когда что использовать? 

```ts
import { BaseModel, Model, Field } from 'maraquia';

@Model({ collectionName: 'used_posts' })
export default class UsedPost extends BaseModel {
  @Field() uri: string;
}
````

Поле `uri` помечено в базе как уникальное, поэтому при сохранении очередного документа через `const`, получал ошибку.

```ts
  const post = new UsedPost({ uri: 'https://www.instagram.com/p/asdasdasdasd_/' }, db.Ig);
  try {
    await post.save();
  } catch (error) {
    console.log(error);
  }
```

Ну и по понятным причинам вылетает такая ошибка.
```
MongoError: E11000 duplicate key error collection: 5cdb1880a6f239ab043a939c_asdas.used_posts index: uri_1 dup key: { : "https://www.instagram.com/p/dsfdasdBzfsad9kasdjxFscp_/" }
    at Function.create (/Users/jeudesprits/Developer/asdsd/node_modules/mongodb-core/lib/error.js:43:12)
    at toError (/Users/jeudesprits/Developer/asdd/node_modules/mongodb/lib/utils.js:149:22)
    at /Users/jeudesprits/Developer/sdsd/node_modules/mongodb/lib/operations/collection_ops.js:1465:39
    at handler (/Users/jeudesprits/Developer/asdsd/node_modules/mongodb-core/lib/topologies/replset.js:1155:22)
    at /Users/jeudesprits/Developer/sdsd/node_modules/mongodb-core/lib/connection/pool.js:397:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  driver: true,
  name: 'MongoError',
  index: 0,
  code: 11000,
  errmsg: 'E11000 duplicate key error collection: 5cdb1880a6f239ab043a939c_asdsd.used_posts index: uri_1 dup key: { : "https://www.instagram.com/p/dsfdasdBzfsad9kasdjxFscp_/" }',
  [Symbol(mongoErrorContextSymbol)]: {}
}
```

А вот через `let` всё как нужно.

**Comment by Riim** [comment]
Привет.

> сохраняются в коллекцию без полей(кроме _id)

Очень странно, речь же про этот код: https://github.com/jeudesprits/ig-web/blob/master/src/dilnozochka-shodiyeva.ts ? Позапускал его сейчас, `uri` корректно сохраняется при первом запуске и ожидаемая ошибка при втором. Может версия монги какая-нибудь старая? У меня `4.0.6`. Попробуй запустить тесты:
```
> git clone https://github.com/Riim/Maraquia.git
> cd Maraquia
> npm i
> npm t
```

Должно получиться так: https://yadi.sk/i/aeDU27dD4nL2mg

> А вот через let всё как нужно.

`const` и `let` никак не влияют на работу кода запускаемого рядом с ними, тут что-то другое.

**Comment by jeudesprits** [comment]
Привет! Тесты с моей бд все прошли. Драйвер Монги последний. 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/36597778/60766314-6bd89880-a0c1-11e9-9dfa-ceede2b0a263.png">

> Позапускал его сейчас, uri корректно сохраняется при первом запуске и ожидаемая ошибка при втором

То что в первый раз сохраняется без ошибки, это следствие того, что ключ `unique`  допускает лишь одну запись `null` для `uri`. А во второй раз, несмотря на то, что казалось бы данные я вставляю другие, выводится ошибка, мол такая запись уже есть. То есть он снова пытается почему-то вставить `null`.  🙁

И у тебя в тестах также везде `let`, заменил на `const`, тесты уже не проходят.

**Comment by Riim** [comment]
> И у тебя в тестах также везде let, заменил на const, тесты уже не проходят.

так же сделал, всё норм. А как именно не проходят, ошибка какая-то?

UPD: какая версия nodejs?

**Comment by jeudesprits** [comment]
**v12.6.0**

```
 FAIL  tests/BaseModel.test.ts (61.486s)
  create
    ✕ null по умолчанию (5011ms)
    ✕ заменяет undefined на null (5006ms)
    ✓ заменяет пустой массив на null (436ms)
    ✓ поле идентификаторов получает значение не наследующее от BaseModel (773ms)
    ✓ поле идентификаторов не получает значение наследующее от BaseModel (674ms)
    ✕ поле идентификатора не получает значение наследующее от BaseModel (5002ms)
    ✓ создаёт встроенный документ (965ms)
    ✓ создаёт внешний документ (1167ms)
    ✓ создаёт встроенные документы (915ms)
    ✓ создаёт внешние документы (654ms)
  update
    ✓ заменяет undefined на null (619ms)
    ✓ заменяет пустой массив на null (474ms)
  save
    ✓ simple save (3065ms)
    ✓ embedded (2907ms)
    ✓ hooks (2746ms)
    ✓ one to one (2605ms)
    ✓ two-way one to one (4768ms)
    ✓ one to many (3857ms)
    ✓ two-way one to many (2856ms)
    ✓ many to many (4486ms)
  fetch
    ✓ simple find (3324ms)
    ✓ fetch field (3466ms)
  remove
    ✓ simple removing (1821ms)
    ✓ hooks (1072ms)
  validation
    ✓ simple validation (995ms)
    ✓ joi (1139ms)

  ● create › null по умолчанию

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● create › заменяет undefined на null

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● create › поле идентификатора не получает значение наследующее от BaseModel

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 23 passed, 26 total
Snapshots:   0 total
Time:        61.943s, estimated 103s
Ran all test suites.
Jest did not exit one second after the test run has completed.
```

**Comment by Riim** [comment]
Какое-то неадекватно большое время выполнения многих тестов, например:
> заменяет пустой массив на null (436ms)

у меня этот тест стабильно выполняется за 1ms. Там просто нечему дольше работать, простейший javascript без какой-либо асинхронщины, промисов и подобного. Попробуй поменять тест так:
```js
	test('заменяет пустой массив на null', () => {
		(global as any)._startTime = Date.now();

		@Model()
		class User extends BaseModel {
			@Field() name: string | null;
		}

		const user = new User();

		user.setField('name', []);

		expect(user.name).toBeNull();

		console.log('!!!', Date.now() - (global as any)._startTime);
	});
```

У меня выводит:
```
  console.log tests/BaseModel.test.ts:286
    !!! 0
```

Если время тоже получится маленьким, то видимо у тебя в работу nodejs что-то вмешивается и сильно мешает.

**Comment by jeudesprits** [comment]
У меня Монга не локально стоит, мб поэтому такое время. 

Заменил:
```
> jest

  console.log tests/BaseModel.test.ts:48
    !!! 1

 FAIL  tests/BaseModel.test.ts (54.264s)
  create
    ✕ null по умолчанию (5008ms)
    ✕ заменяет undefined на null (5003ms)
    ✓ заменяет пустой массив на null (209ms)
    ✓ поле идентификаторов получает значение не наследующее от BaseModel (166ms)
    ✓ поле идентификаторов не получает значение наследующее от BaseModel (160ms)
    ✓ поле идентификатора не получает значение наследующее от BaseModel (167ms)
    ✓ создаёт встроенный документ (148ms)
    ✓ создаёт внешний документ (168ms)
    ✓ создаёт встроенные документы (179ms)
    ✓ создаёт внешние документы (154ms)
  update
    ✓ заменяет undefined на null (166ms)
    ✓ заменяет пустой массив на null (171ms)
  save
    ✓ simple save (670ms)
    ✓ embedded (686ms)
    ✓ hooks (478ms)
    ✓ one to one (3219ms)
    ✓ two-way one to one (1163ms)
    ✓ one to many (1186ms)
    ✕ two-way one to many (3899ms)
    ✕ many to many (7995ms)
  fetch
    ✕ simple find (6306ms)
    ✓ fetch field (4684ms)
  remove
    ✓ simple removing (4500ms)
    ✓ hooks (3944ms)
  validation
    ✓ simple validation (1160ms)
    ✓ joi (534ms)

  ● create › null по умолчанию

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● create › заменяет undefined на null

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● save › two-way one to many

    TypeError: Cannot read property 'pets' of null

      518 | 
      519 |             expect(petDoc).toMatchObject({
    > 520 |                     _id: ownerDoc.pets[0],
          |                                   ^
      521 |                     name: 'Tatoshka',
      522 |                     owner: ownerDoc._id
      523 |             });

      at Object.<anonymous> (tests/BaseModel.test.ts:520:18)

  ● save › many to many

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: 

      528 |     });
      529 | 
    > 530 |     test('many to many', async () => {
          |     ^
      531 |             @Model({
      532 |                     collectionName: 'User'
      533 |             })

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/BaseModel.test.ts:530:2)
      at Object.<anonymous> (tests/BaseModel.test.ts:281:1)

  ● fetch › simple find

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: 

      599 | 
      600 | describe('fetch', () => {
    > 601 |     test('simple find', async () => {
          |     ^
      602 |             @Model({
      603 |                     collectionName: 'Pet'
      604 |             })

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/BaseModel.test.ts:601:2)
      at Object.<anonymous> (tests/BaseModel.test.ts:600:1)

  ● fetch › simple find

    TypeError: Cannot read property '_id' of null

      578 |                     _id: group1Doc.users[0],
      579 |                     name: 'Dmitry',
    > 580 |                     groups: [group1Doc._id, group2Doc._id]
          |                                                       ^
      581 |             });
      582 |             expect(user2Doc).toMatchObject({
      583 |                     _id: group2Doc.users[1],

      at Object.<anonymous> (tests/BaseModel.test.ts:580:38)

  ● fetch › simple find

    MongoError: Cannot create collection MaraquiaTest.Owner - database is in the process of being dropped.

      at Function.create (node_modules/mongodb-core/lib/error.js:43:12)
      at toError (node_modules/mongodb/lib/utils.js:149:22)
      at node_modules/mongodb/lib/operations/collection_ops.js:859:39
      at handler (node_modules/mongodb-core/lib/topologies/replset.js:1155:22)
      at node_modules/mongodb-core/lib/connection/pool.js:397:18

Test Suites: 1 failed, 1 total
Tests:       5 failed, 21 passed, 26 total
Snapshots:   0 total
Time:        55.275s, estimated 62s
Ran all test suites.
```

**Comment by Riim** [comment]
> У меня Монга не локально стоит, мб поэтому такое время.

это объясняет в 2-5 раз большее время в секциях save, fetch и remove, но никак не объясняет в сотни раз большее время в остальных секциях, где maraquia к монге никак не прикасается. Хотя нет, вот здесь прикасается:
```js
afterEach(() => {
	getDefaultInstance().then(m => m.db.dropDatabase());
});
```

Попробуй закомментить этот блок и все тесты кроме `test('null по умолчанию'`, может на сбросе БД какие-то проблемы возникают. Если так, то тест пройдёт за пару миллисекунд.

Если не подтвердится, то попробуй ещё самостоятельно подебажить (я бы и рад сам, но у меня никак не повторяется, попробовал уже на MacOS, Ubuntu, Windows, везде всё отлично). Для vscode я делаю так:
1) в файл `.vscode/launch.json` добавляю следующее:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/jest/bin/jest.js",
        "--runInBand"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "port": 9229
    }
  ]
}
```
2) в консоли запускаю `node --inspect-brk ./node_modules/jest/bin/jest.js --runInBand`
3) дальше брейкпоинт и запуск отладки: https://yadi.sk/i/6SfLePOq_kbc4Q

**Comment by jeudesprits** [comment]
Тест прошёл, время чуть больше секунды 🤷‍♂️. Попробую на днях продебажить. Я ещё хотел спросить, а всегда ли нужно добавлять тип `... | null`?
```ts
@Model()
		class User extends BaseModel {
			@Field() name: string | null;
		}
```

**Comment by Riim** [comment]
> всегда ли нужно добавлять тип ... | null

для обязательных полей добавлять не нужно, для _не_обязательных только если хочешь чтобы typescript помогал тебе не допускать ошибки чтения из null.

**Comment by Riim** [comment]
@jeudesprits получилось разобраться или мне просто закрыть issue?

**Comment by jeudesprits** [comment]
Проблема так и осталась. Пересел на нативный драйвер.

**Comment by jeudesprits** [comment]
> @jeudesprits получилось разобраться или мне просто закрыть issue?

Проблема так и осталась. Пересел на нативный драйвер.

**Comment by Riim** [comment]
А раньше какой был? С нативным тоже остаётся?

**Comment by jeudesprits** [comment]
@Riim Не понял вас. Раньше я пытался работать собственно с этим пакетом. Пересел на нативный драйвер https://www.npmjs.com/package/mongodb Проблема исчезла. Ничего особо не менял.

**Comment by Riim** [comment]
Я подумал вместо пакета mongodb использовался какой-то альтернативный, но так же в сочетании с Maraquia. Ладно, если будет время и желание, то попробуйте сделать и выложить какой-то минимальный пример где проблема проявляется. Мне всё-таки хотелось бы разобраться. А пока я закрою ишъю если вы не против?

**Comment by jeudesprits** [comment]
@Riim Да, конечно.
